[package]
name = "bevy_ecs"
version = "0.5.0"
edition = "2018"
authors = [
    "Bevy Contributors <bevyengine@gmail.com>",
    "Carter Anderson <mcanders1@gmail.com>",
]
description = "Bevy Engine's entity component system"
homepage = "https://bevyengine.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT"
keywords = ["ecs", "game", "bevy"]
categories = ["game-engines", "data-structures"]

[features]
trace = []

[dependencies]
bevy_ecs_macros = { version = "0.5.0" }
fixedbitset = "0.4"
thiserror = "1.0"
downcast-rs = "1.2"
serde = "1"
